### ISSUE TITLE
Build failure with the new hyprland color management protocol

### ISSUE THREAD

**Issue by Soliprem** [Duckonaut/split-monitor-workspaces#166]
```
split-monitor-workspaces> [1/2] Compiling C++ object libsplit-monitor-workspaces.so.p/src_main.cpp.o
split-monitor-workspaces> FAILED: libsplit-monitor-workspaces.so.p/src_main.cpp.o
split-monitor-workspaces> g++ -Ilibsplit-monitor-workspaces.so.p -I. -I.. -I../include -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/protocols -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland -I/nix/store/s2c7885imhhnfxpkcl1qmprqkv7x8cib-pixman-0.44.2/include/pixman-1 -I/nix/store/f9vp3fdvg57pacplrx8csbiwqw0vv91s-libdrm-2.4.124-dev/include -I/nix/store/f9vp3fdvg57pacplrx8csbiwqw0vv91s-libdrm-2.4.124-dev/include/libdrm -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++23 -DWLR_USE_UNSTABLE -fno-gnu-unique -fPIC -MD -MQ libsplit-monitor-workspaces.so.p/src_main.cpp.o -MF libsplit-monitor-workspaces.so.p/src_main.cpp.o.d -o libsplit-monitor-workspaces.so.p/src_main.cpp.o -c ../src/main.cpp
split-monitor-workspaces> In file included from /nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/src/config/ConfigManager.hpp:14,
split-monitor-workspaces>                  from ../src/main.cpp:4:
split-monitor-workspaces> /nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/src/helpers/Monitor.hpp:15:10: fatal error: protocols/types/ColorManagement.hpp: No such file or directory
split-monitor-workspaces>    15 | #include "protocols/types/ColorManagement.hpp"
split-monitor-workspaces>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
split-monitor-workspaces> compilation terminated.
split-monitor-workspaces> ninja: build stopped: subcommand failed.
error: builder for '/nix/store/mn3f9r0lpflfpn5rahk18vlvwr7gjlb4-split-monitor-workspaces-0.1.drv' failed with exit code 1;
       last 25 log lines:
       >     buildtype    : plain
       >     includedir   : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/include
       >     infodir      : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/share/info
       >     libdir       : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/lib
       >     libexecdir   : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/libexec
       >     localedir    : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/share/locale
       >     mandir       : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/share/man
       >     prefix       : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1
       >     sbindir      : /nix/store/6lzm0vgahrdc79lparbg3cm699g9n6y3-split-monitor-workspaces-0.1/sbin
       >     wrap_mode    : nodownload
       >
       > Found ninja-1.12.1 at /nix/store/2f0n798y2p347z6rbij490ral0vq2z4b-ninja-1.12.1/bin/ninja
       > mesonConfigurePhase: enabled\ parallel\ building
       > Running phase: buildPhase
       > build flags: -j24
       > [1/2] Compiling C++ object libsplit-monitor-workspaces.so.p/src_main.cpp.o
       > FAILED: libsplit-monitor-workspaces.so.p/src_main.cpp.o
       > g++ -Ilibsplit-monitor-workspaces.so.p -I. -I.. -I../include -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/protocols -I/nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland -I/nix/store/s2c7885imhhnfxpkcl1qmprqkv7x8cib-pixman-0.44.2/include/pixman-1 -I/nix/store/f9vp3fdvg57pacplrx8csbiwqw0vv91s-libdrm-2.4.124-dev/include -I/nix/store/f9vp3fdvg57pacplrx8csbiwqw0vv91s-libdrm-2.4.124-dev/include/libdrm -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++23 -DWLR_USE_UNSTABLE -fno-gnu-unique -fPIC -MD -MQ libsplit-monitor-workspaces.so.p/src_main.cpp.o -MF libsplit-monitor-workspaces.so.p/src_main.cpp.o.d -o libsplit-monitor-workspaces.so.p/src_main.cpp.o -c ../src/main.cpp
       > In file included from /nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/src/config/ConfigManager.hpp:14,
       >                  from ../src/main.cpp:4:
       > /nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/src/helpers/Monitor.hpp:15:10: fatal error: protocols/types/ColorManagement.hpp: No such file or directory
       >    15 | #include "protocols/types/ColorManagement.hpp"
       >       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > compilation terminated.
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/mn3f9r0lpflfpn5rahk18vlvwr7gjlb4-split-monitor-workspaces-0.1.drv'.
error: 1 dependencies of derivation '/nix/store/6y1d9pkd23zzahq9r8cqrs2s9ljxafgz-etc-xdg-hypr-hyprland.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2zb2mcxwyd4x30kryqc889b9fkf9yvb6-etc.drv' failed to build
┏━ 1 Errors:
 ⋮
┃        >                  from ../src/main.cpp:4:
┃        > /nix/store/yymr4zdvqwkdfdvhac4l0rqyvfm1184s-hyprland-0.47.0+date=2025-02-26_002cd91-dev/include/hyprland/src/helpers/Monitor.hpp:15:10: fatal error: protocols/types/ColorManagement.hpp: No such file or directory
┃        >    15 | #include "protocols/types/ColorManagement.hpp"
┃        >       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
┃        > compilation terminated.
┃        > ninja: build stopped: subcommand failed.
┃        For full logs, run 'nix log /nix/store/mn3f9r0lpflfpn5rahk18vlvwr7gjlb4-split-monitor-workspaces-0.1.drv'.
```

**Comment by zjeffer** [comment]
Hyprland issue, I commented on the offending PR (https://github.com/hyprwm/Hyprland/pull/9444/files#r1972357664)

**Comment by Soliprem** [comment]
looks fixed now
