### ISSUE TITLE
Failed to build with Hyprland 0.38.1

### ISSUE THREAD

**Issue by hdhog** [Duckonaut/split-monitor-workspaces#64]
try to build commit  `b0ee3953eaeba70f3fba7c4368987d727779826a`
```
[1/2] Compiling C++ object libsplit-monitor-workspaces.so.p/src_main.cpp.o
FAILED: libsplit-monitor-workspaces.so.p/src_main.cpp.o 
g++ -Ilibsplit-monitor-workspaces.so.p -I. -I.. -I../include -I/nix/store/pnx1hwlzpjpxrwsqfq1m0hc9kpykjacv-hyprland-0.38.1-dev/include -I/nix/store/pnx1hwlzpjpxrwsqfq1m0hc9kpykjacv-hyprland-0.38.1-dev/include/hyprland/protocols -I/nix/store/pnx1hwlzpjpxrwsqfq1m0hc9kpykjacv-hyprland-0.38.1-dev/include/hyprland/wlroots -I/nix/store/73lsxaii5sk9zgm7g53mca4a65a9i5xh-
pixman-0.43.4/include/pixman-1 -I/nix/store/njw23bh48h17f4mxb1zywv1gn89brz6r-libdrm-2.4.120-dev/include -I/nix/store/njw23bh48h17f4mxb1zywv1gn89brz6r-libdrm-2.4.120-dev/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++23 -DWLR_USE_UNSTABLE -fPIC -MD -MQ libsplit-monitor-workspaces.so.p/src_main.cpp.o -MF libsplit-monito
r-workspaces.so.p/src_main.cpp.o.d -o libsplit-monitor-workspaces.so.p/src_main.cpp.o -c ../src/main.cpp
../src/main.cpp: In function 'void changeMonitor(bool, const std::string&)':
../src/main.cpp:99:55: error: base operand of '->' is not a pointer
   99 |     int nextWorkspaceID = nextMonitor->activeWorkspace->m_iID;
      |                                                       ^~
../src/main.cpp: In function 'void fixWorkspaceArrangement()':
../src/main.cpp:145:13: error: 'PHLWORKSPACE' was not declared in this scope
  145 |             PHLWORKSPACE workspacePtr = g_pCompositor->getWorkspaceByName(workspace);
      |             ^~~~~~~~~~~~
../src/main.cpp:146:17: error: 'workspacePtr' was not declared in this scope; did you mean 'workspace'?
  146 |             if (workspacePtr != nullptr) {
      |                 ^~~~~~~~~~~~
      |                 workspace
../src/main.cpp: In function 'void mapWorkspacesToMonitors()':
../src/main.cpp:198:13: error: 'PHLWORKSPACE' was not declared in this scope
  198 |             PHLWORKSPACE workspace = g_pCompositor->getWorkspaceByName(workspaceName);
      |             ^~~~~~~~~~~~
../src/main.cpp:200:17: error: 'workspace' was not declared in this scope; did you mean 'CWorkspace'?
  200 |             if (workspace != nullptr) {
      |                 ^~~~~~~~~
      |                 CWorkspace

```

**Comment by zjeffer** [comment]
If you're using hyprpm, you should be able to use the pins feature to build split-monitor-workspace on the commit that works with Hyprland 0.38.1:

https://github.com/Duckonaut/split-monitor-workspaces/blob/main/hyprpm.toml#L5

**Comment by hdhog** [comment]
i  use custom nixos overlay for build this plugin. thanks, pinned commit build successfully. 

i suppose split-monitor needs versioning close with hyprland :)

**Comment by zjeffer** [comment]
> i suppose split-monitor needs versioning close with hyprland :)

Yes, most plugins do. Hyprland code changes frequently so we have to keep up ;)

We should use the pins feature more often though, preferably every time there's a new Hyprland release.
